#全球直连
payload: 
 - DOMAIN-SUFFIX,acl4.ssr
 - DOMAIN-SUFFIX,ip6-localhost
 - DOMAIN-SUFFIX,ip6-loopback
 - DOMAIN-SUFFIX,local
 - DOMAIN-SUFFIX,localhost
 - IP-CIDR,10.0.0.0/8,no-resolve
 - IP-CIDR,100.64.0.0/10,no-resolve
 - IP-CIDR,127.0.0.0/8,no-resolve
 - IP-CIDR,172.16.0.0/12,no-resolve
 - IP-CIDR,192.168.0.0/16,no-resolve
 - IP-CIDR,198.18.0.0/16,no-resolve
 - IP-CIDR6,::1/128,no-resolve
 - IP-CIDR6,fc00::/7,no-resolve
 - IP-CIDR6,fe80::/10,no-resolve
 - IP-CIDR6,fd00::/8,no-resolve
 - DOMAIN,router.asus.com
 - DOMAIN-SUFFIX,hiwifi.com
 - DOMAIN-SUFFIX,leike.cc
 - DOMAIN-SUFFIX,miwifi.com
 - DOMAIN-SUFFIX,my.router
 - DOMAIN-SUFFIX,p.to
 - DOMAIN-SUFFIX,peiluyou.com
 - DOMAIN-SUFFIX,phicomm.me
 - DOMAIN-SUFFIX,routerlogin.com
 - DOMAIN-SUFFIX,tendawifi.com
 - DOMAIN-SUFFIX,zte.home
 - DOMAIN-SUFFIX,265.com
 - DOMAIN-SUFFIX,2mdn.net
 - DOMAIN-SUFFIX,alt1-mtalk.google.com
 - DOMAIN-SUFFIX,alt2-mtalk.google.com
 - DOMAIN-SUFFIX,alt3-mtalk.google.com
 - DOMAIN-SUFFIX,alt4-mtalk.google.com
 - DOMAIN-SUFFIX,alt5-mtalk.google.com
 - DOMAIN-SUFFIX,alt6-mtalk.google.com
 - DOMAIN-SUFFIX,alt7-mtalk.google.com
 - DOMAIN-SUFFIX,alt8-mtalk.google.com
 - DOMAIN-SUFFIX,app-measurement.com
 - DOMAIN-SUFFIX,c.android.clients.google.com
 - DOMAIN-SUFFIX,cache.pack.google.com
 - DOMAIN-SUFFIX,clickserve.dartsearch.net
 - DOMAIN-SUFFIX,clientservices.googleapis.com
 - DOMAIN-SUFFIX,crl.pki.goog
 - DOMAIN-SUFFIX,dl.google.com
 - DOMAIN-SUFFIX,dl.l.google.com
 - DOMAIN-SUFFIX,fonts.googleapis.com
 - DOMAIN-SUFFIX,fonts.gstatic.com
 - DOMAIN-SUFFIX,googletagmanager.com
 - DOMAIN-SUFFIX,googletagservices.com
 - DOMAIN-SUFFIX,gtm.oasisfeng.com
 - DOMAIN-SUFFIX,imasdk.googleapis.com
 - DOMAIN-SUFFIX,mtalk.google.com
 - DOMAIN-SUFFIX,ocsp.pki.goog
 - DOMAIN-SUFFIX,recaptcha.net
 - DOMAIN-SUFFIX,redirector.gvt1.com
 - DOMAIN-SUFFIX,safebrowsing-cache.google.com
 - DOMAIN-SUFFIX,safebrowsing.googleapis.com
 - DOMAIN-SUFFIX,settings.crashlytics.com
 - DOMAIN-SUFFIX,ssl-google-analytics.l.google.com
 - DOMAIN-SUFFIX,ssl.gstatic.com
 - DOMAIN-SUFFIX,toolbarqueries.google.com
 - DOMAIN-SUFFIX,tools.google.com
 - DOMAIN-SUFFIX,tools.l.google.com
 - DOMAIN-SUFFIX,update.googleapis.com
 - DOMAIN-SUFFIX,www-googletagmanager.l.google.com
 - DOMAIN-SUFFIX,www.gstatic.com
